version: '3.7'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    env_file:
      - configs/config.env
  db:
    image: postgres:13-alpine
    restart: always
    env_file:
      - configs/config.env
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
